### ISSUE TITLE
可与加个开机自起吗

### ISSUE THREAD

**Issue by poify** [Akegarasu/cocogoat-signin#7]

**Comment by Akegarasu** [comment]
请自己设置系统达到开机自起，本程序不会支持

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: poify ***@***.***>
发送时间: Friday, September 30, 2022 3:50:26 PM
收件人: Akegarasu/cocogoat-signin ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Akegarasu/cocogoat-signin] 可与加个开机自起吗 (Issue #7)


―
