### ISSUE TITLE
提示cookie过期 但是没有报错信息

### ISSUE THREAD

**Issue by MJSummer** [Akegarasu/cocogoat-signin#9]
[椰羊签到][2022-10-21 21:15:26][WARNING]: 签到失败~ 可能是 cookie 过期了请重新获取cookie! 报错:

**Comment by Akegarasu** [comment]
这种情况一般是触发验证码了

**Comment by MJSummer** [comment]
是需要重新获取一遍ck吗

**Comment by Akegarasu** [comment]
不是，是被检测到可能有异常触发验证码。这个目前没办法解决

**Comment by MJSummer** [comment]
明白了 奖励每天手领了需要
